version: "3.9"
services:
  app:
    build: .
    ports:
      - "8081:8080"
    volumes:
        - .:/app
    depends_on:
      - db
    restart: on-failure
  db:
    image: mysql:8.0.31
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-password
      MYSQL_DATABASE: my-database
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

volumes:
    db: